@include('layouts.client.header')
@include('layouts.client.thongBao')
@include('layouts.client.header_top')
@yield('content')
@include('layouts.client.footer')
@include('layouts.client.footer_product')
@include('layouts.client.footer_link')